#pragma once
#define TOKEN_ADD "+"
#define TOKEN_SUB "-"
#define TOKEN_MUL "*"
#define TOKEN_DIV "/"
#define TOKEN_MOD "%"
#define TOKEN_NOT "!"
#define TOKEN_OR "or"
#define TOKEN_AND "and"
#define TOKEN_EQ "="
#define TOKEN_N_EQ "!="
#define TOKEN_GT ">"
#define TOKEN_LW "<"
#define TOKEN_GT_E ">="
#define TOKEN_LW_E "<="
#define TOKEN_POP "pop"
#define TOKEN_DUP "dup"
#define TOKEN_SWAP "swap"
#define TOKEN_OVER "over"
#define TOKEN_IF "if"
#define TOKEN_ELSE "else"
#define TOKEN_BEGIN "begin"
#define TOKEN_WHILE "while"
#define TOKEN_END "end"
#define TOKEN_PRINT "echo"

int str_to_token(const char *str);